name: projects-student-template
dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- ruff
- pre-commit
- nbconvert
- pytest
- ipykernel
- pip
- pip:
    - nbmake
